name: Test read JSON 
on: workflow_dispatch

jobs: 
  readJob:
    name: Test for using object from JSON file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat app.json`
          echo "::set-output name=params::${{content}}"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.params).config}}"
