name: Test read JSON 
on: workflow_dispatch

jobs: 
  readJob:
    name: Test for using object from JSON file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat app.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "$content"
          echo "::set-output name=params::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.params).version}}"
